### ISSUE TITLE
Question on TheHive5 compatibility

### ISSUE THREAD

**Issue by faisalusuf** [jaredjennings/helm-thehive#22]
Hi Jared,

This is a great project. Wonder if thehive5 is also compatible?

Thanks

**Comment by jaredjennings** [comment]
I said this in the Discord a bit ago, but that's not so durable or searchable as this GitHub issue.

I don't know if TheHive5 is compatible with this Helm chart. I'm going to leave version-5 support entirely up to StrangeBee, and recommend that you pay them money.
