### ISSUE TITLE
subcharts? (e.g. no Cortex support)

### ISSUE THREAD

**Issue by jaredjennings** [jaredjennings/helm-thehive#5]
Cortex, MISP, Shuffler, Node-RED, etc.

These should be separately developed, then depended on from here, in the same way Cassandra is. This way you could install e.g. Cortex somewhere else independently, like the design diagrams on thehive-project.org suggest.

Some cross-chart finesse would still be needed to let TheHive and Cortex share an Elasticsearch cluster.

**Comment by jaredjennings** [comment]
https://github.com/jaredjennings/helm-cortex

**Comment by jaredjennings** [comment]
Elasticsearch sharing finesse is not necessary provided that the Elasticsearch cluster is set up by neither chart, which is the change I have just wreaked. See the commit messages for more on the rationale.

**Comment by jaredjennings** [comment]
Hooking TheHive up to Cortex requires first setting up the organization(s) in Cortex, and some service accounts with API keys, one in each. If this Helm chart were an operator instead, perhaps that sort of reaching inside the app is something we could do (see also #4). Likewise for MISP, I think there's stuff you need to do inside the app before you hook them up.

So for now the other charts are peers, not subcharts. It means that getting the whole thing up is a matter to be guided through and not some kind of single glorious YAML incantation. That's fine, for now at least.

**Comment by mwmahlberg** [comment]
My 2 cents on this: Overcomplicating helm charts comes with its own problems.

What you could do is to have a multi-container helm chart, and only include optional containers on the user's request, eg.

```
cortex:
  enabled: false
```

and then a conditional container in the deployment. Also, keep in mind that people are most likely to create a deployment descriptor one way or the other, including the tidbits they need or deem appropriate.
